[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

# [programs.localnet]
[programs.devnet]
counter = "B3oFEmT9LiYrbd8CknDvbkLynbcmJWWQ5cqwoXGuqRfi"
vault = "4trU6PxX9bq7yAkFaCr4SmfbzddSEbbnufuZ8CjpBy1R"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
